[tools]
python = "pypy3.10-7.3.17"
# rust = "1.86.0"
"cargo:pahcer" = "latest"

[env]
_.python.venv = { path = ".venv" }

[tasks.cppy]
run = "cat main.py | wl-copy"

[tasks.cpcpp]
run = "oj-bundle main.cpp -I /home/hidehic0/src/github.com/hidehic0/library_cpp | wl-copy"
