[project]
name = "my_atcoder_code"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "ac-library-python",
  "aclogin>=0.2.1",
  "debugpy>=1.8.17",
  "online-judge-api-client",
  "online-judge-tools",
  "online-judge-verify-helper>=5.6.0",
  "pulp==3.2.0",
  "sortedcontainers>=2.4.0",
]

[tool.ruff]
line-length = 88
select = ["C9", "E", "F", "W", "I"]

[tool.ruff.lint]
ignore = ["F401", "E402", "F811", "E741", "E702"]

[tool.uv.sources]
ac-library-python = { git = "https://github.com/not522/ac-library-python" }
online-judge-tools = { git = "https://github.com/hidehic0/oj.git" }
online-judge-api-client = { git = "https://github.com/hidehic0/api-client.git" }
