language = 'Python'
name = 'PyPy'

version = 'v3.10-v7.3.17'

install = '''
cd /tmp

sudo apt-get update

# インストール時の依存関係
sudo apt-get install -y git wget bzip2

# ライブラリの依存関係
sudo apt-get install -y gcc g++ gfortran libopenblas-dev liblapack-dev pkg-config libgeos-dev

# ビルド済みバイナリをインストール
wget https://downloads.python.org/pypy/pypy3.10-v7.3.17-linux64.tar.bz2
tar jxvf pypy3.10-v7.3.17-linux64.tar.bz2

cd pypy3.10-v7.3.17-linux64

# pipを有効化
./bin/pypy3 -m ensurepip

# パスが通る所へ移動
cp -r ./bin/* /usr/local/bin
cp -r ./include/* /usr/local/include
cp -r ./lib/* /usr/local/lib

# ライブラリをインストール
pip3 install --break-system-packages \
    numpy==2.2.3 \
    scipy==1.15.2 \
    networkx==3.4.2 \
    sympy==1.13.3 \
    sortedcontainers==2.4.0 \
    more-itertools==10.6.0 \
    shapely==2.0.7 \
    bitarray==3.1.0 \
    PuLP==3.0.2 \
    mpmath==1.3.0 \
    pandas==2.2.3 \
    z3-solver==4.14.0.0 \
    scikit-learn==1.6.1 \
    cppyy==3.5.0 \
    git+https://github.com/not522/ac-library-python
'''
