name: close daily_virtual_contests issue
on:
  push:
    paths:
      - .github/workflows/stale.yaml
  schedule:
    - cron: "0 3 * * *"

jobs:
  close-issues:
    permissions:
      actions: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          only-labels: daily_virtual_contests
          days-before-stale: 1
          days-before-close: 0
          close-issue-label: Stale
