name: close daily_virtual_contests issue
on:
  push:
    paths:
      - .github/workflows/stale.yaml
  schedule:
    - cron: "0 3 * * *"

jobs:
  close-issues:
    permissions:
      actions: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
        with:
          only-labels: daily_virtual_contests
          days-before-stale: 1
          days-before-close: 0
          close-issue-label: Stale
