name: close daily_virtual_contests issue
on:
  push:
    paths:
      - .github/workflows/stale.yaml
  schedule:
    - cron: "0 3 * * *"

jobs:
  close-issues:
    permissions:
      actions: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
        with:
          only-labels: daily_virtual_contests
          days-before-stale: 1
          days-before-close: 0
          close-issue-label: Stale
